---
# tasks file for myrole
- name: install tomcat7 on redhat7
  yum:
    name: tomcat
    state: present
  when: ansible_os_family== "RedHat"

- name: copy the tomcat config file on all nodes
  template:
    src: templates/tomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  when: ansible_os_family== "RedHat"

- name: install tom admin packages
  yum: 
    name: "{{item}}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps

- name: copy the tom user file on nodes
  template:
    src: templates/tomusers.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: tomstart
  when: ansible_os_family== "RedHat"
